# -----------------------------
# URL / 根路径
# -----------------------------
url: https://yogurt-shadow.github.io   # 你 GitHub Pages 站点 URL
root: /blog/                           # 博客部署在 /blog/ 下

# -----------------------------
# Hexo 生成目录（不变）
# -----------------------------
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# -----------------------------
# 部署（不使用 gh-pages）
# -----------------------------
deploy:
  type: ''
